### ISSUE TITLE
Seems not to be compatible with FW 2.29.23

### ISSUE THREAD

**Issue by robbyb67** [alexreinert/homematic_check_mk#1]
The agent is not listed in "additional Software" and does not work

**Comment by alexreinert** [comment]
I'm pretty sure, that is compatible with FW 2.29.23 as it is running on all of my test devices. Can you please provide some more information?

**Comment by robbyb67** [comment]
Of cause: I managed to install it manually.

The tgz is - when uploaded by web-ui - in /var

If I manually unpack and run the ./update_scipt in a ssh session everything is fine.
Maybe something was changed how CCU handles a new_firmware.tar.gz in /var?

**Comment by alexreinert** [comment]
What device are you using? (Original CCU2, piVCCU, RaspberryMatic, ...)

**Comment by robbyb67** [comment]
The original one as self-assembly by ELV.

**Comment by alexreinert** [comment]
I could reproduce it with the original CCU2 (and only with the CCU2, piVCCU and RaspberryMatic are working without issue), but I need to have a deeper look into it.

**Comment by alexreinert** [comment]
Fixed in release 1.3

**Comment by robbyb67** [comment]
This check is really a little jewel. Thanks a lot for that project.
